# Generated by Django 4.2.5 on 2023-09-20 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Littlelemon_Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='BookingDate',
            new_name='BookingDateooo',
        ),
    ]
